layout: sidebar
style: light
theme: null

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    forks: true
    projects:
      - OpenDVP
      - Bio
      - figurinhator
      - tensorflow-1.12.0-cp37-cp37m-linux_x86_64
      - CS231n-Assignment-2
      - CS231n-Assignment-3


social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: adrianodennanni
  medium: adrianodennanni
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: adrianodennanni
  # unsplash: your_username
  # vk: your_username
  website: adrianodennanni.github.io
  # youtube: your_username

# topics:
#   - name: Deep Learning
#   - name: Deployment
